### ISSUE TITLE
python example in auth.md for python authentication looks outdated

### ISSUE THREAD

**Issue by jboeuf** [grpc/grpc.github.io#207]
Please update the new "scopeless" creds awesomeness.

Thanks!

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle would you be able to point to some documentation/examples around this?

**Comment by nathanielmanistaatgoogle** [comment]
This will go hand-in-hand with [gRPC issue 7548](https://github.com/grpc/grpc/issues/7548). @kpayson64, I've been meaning to get to this for the last week or so but haven't been operating at full steam...

**Comment by kpayson64** [comment]
I think #7548 is a little different.  The example for #7548 should still use scoped credentials, but should recycle the oauth object so we don't request new credentials in every loop.

I'm pushing the "scopeless" documentation off GA, and will document the scopeless use with #6860 because we will publish some convenience wrappers for scopeless/scoped creds and update the documentation there.

**Comment by jtattermusch** [comment]
@kpayson64, can we update / close this issue?

**Comment by kpayson64** [comment]
Yes, we have the latest credentials use documented.

**Comment by kpayson64** [comment]
@jtattermusch Looks like I don't have "close" privileges on this repository though, can you close this issue?
