### ISSUE TITLE
Ruby: Bidirectional Stream Example

### ISSUE THREAD

**Issue by davissp14** [grpc/grpc.github.io#488]
Link: https://github.com/grpc/grpc/issues/10526

**Comment by jtattermusch** [comment]
@apolcyn  please address or close.

**Comment by apolcyn** [comment]
I'd like to point everyone looking for more examples like this to take a look at the interop test [client](https://github.com/grpc/grpc/blob/master/src/ruby/pb/test/client.rb) and [server](https://github.com/grpc/grpc/blob/master/src/ruby/pb/test/server.rb) as well as the benchmarking "QPS" test [client](https://github.com/grpc/grpc/blob/master/src/ruby/qps/client.rb) and [server](https://github.com/grpc/grpc/blob/master/src/ruby/qps/server.rb).

For background on the interop client and server, see the [high level descriptions of the interop test cases](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md) 

I'd like to refer to those tests since they are a good source of examples of other things too, such as use of metadata handling and e.g., non-OK status codes.

Closing this, but if it doesn't look like those tests are sufficient as examples, please don't hesitate to reopen this issue and we can revisit.
