### ISSUE TITLE
Fix blog post TOC formatting

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc.github.io#528]
The TOC for the blog post is broken with the latest post. 
We need to fix this, might be good to look at how the posts could be layed out. Ideally, we just want a single listing of all the posts published so far  to help visibility.

**Comment by LisaFC** [comment]
I think the TOC currently is how it's always been set up to look, it's just the standard "pulls all the headings from the page and makes a TOC" script - it's just more obvious because that blog post has loads of headings. If we want a TOC of all the blog posts we'll have to do something custom. Let me take a look.

**Comment by LisaFC** [comment]
We're also showing the entirety of the most recent blog post on the blog index/landing page, I don't know do we want to continue to do this?

**Comment by hsaliak** [comment]
I do not think we should do that. We should only show a snippet followed by
"Read More' so that the list of all available blog posts show up.

**Comment by LisaFC** [comment]
As far as I can tell from reading about the pagination plugin, because we've set an excerpt separator in the _config file, you need to actually add it to the doc where you want it to stop pulling out content for the excerpt - it's why we're currently getting the entire post.

We can also change the pagination settings so that more posts appear on the landing page (currently it's only two), and I think it should be easy enough to change the toc just for this page type so it creates a list of blog posts (or we could just skip it entirely).  I'll mock it up in my fork and you can have a look.

**Comment by LisaFC** [comment]
Here's what it looks like with a shorter snippet 

There's no TOC because there aren't any headings in the snippets.

**Comment by LisaFC** [comment]
Now has a list of blog posts on the right. Not entirely sure how I feel about it, I wonder would we be better without a toc at all.

**Comment by LisaFC** [comment]
Pingity ping?

**Comment by hsaliak** [comment]
Sorry for the delay -- the example cited looks really good, shall we go ahead and do that?

**Comment by LisaFC** [comment]
Sure!

**Comment by hsaliak** [comment]
http://www.grpc.io/blog/ looks really good now, closing this issue!
